### ISSUE TITLE
能否改成调用ChatGPT吗？

### ISSUE THREAD

**Issue by chrysoljq** [RIvance/mirai-openai-gpt-chatbot#1]
根据配置文件，可以看出是调用的 `text-davinci-003`，该模型是付费的（虽然 OpenAI 提供了 18$ 的免费额度），两天我就用掉了 7 刀，而 `ChatGPT` 目前是免费的。

此外，直接调用 API 并不能保持会话，而无法联系上文。

**Comment by RIvance** [comment]
之后如果有时间的话再写一个吧, 目前这个是基于 openai 的一个第三方 java api 做的, 要改的话基本相当于重写. 另外就是 ChatGPT 的 api 目前中国大陆的 ip 好像是没法用的, 需要科学上网.

**Comment by RIvance** [comment]
目前openai官方改了登录认证方式后大部分基于chatgpt的api都挂了, 这个issue先close了, 等出来能用的看情况再说吧
